### ISSUE TITLE
Drawer Controller Doesn't work despite following layout

### ISSUE THREAD

**Issue by CodeF53** [benfah/SimpleDrawers#10]
Running on 20w18a (with the API) with no other mods installed, I cant get the drawer controller to work.

Following the screenshots on the mod page, I get this setup:
![2020-05-08_13 40 16](https://user-images.githubusercontent.com/37855219/81442816-80e2e580-9131-11ea-9217-3fb6411db433.png)
![2020-05-08_13 40 21](https://user-images.githubusercontent.com/37855219/81442817-82141280-9131-11ea-8018-6d048ae2c89d.png)
![2020-05-08_13 40 25](https://user-images.githubusercontent.com/37855219/81442820-82aca900-9131-11ea-9c6c-8ce3e41b7fdc.png)

With this, right clicking on the drawer controller does nothing.

**Comment by benfah** [comment]
The drawer controller is supposed to let you input items into the controller itself through a hopper, which then fills the items into the 3x3 area of drawers. ;)

**Comment by JoshMayberry** [comment]
Is this information documented anywhere? The wiki just links to the git hub code page

**Comment by benfah** [comment]
You can find a setup guide on the 'How to use' section on the main page of the mod.
