### ISSUE TITLE
Shift+Left Click on an inventory item while the drawer GUI is opened freezes the game

### ISSUE THREAD

**Issue by Ayutac** [benfah/SimpleDrawers#11]
If I open the drawer GUI on a drawer I have an item in and then Shift+Left Click on any item in the inventory the game freezes.

**Comment by Adirelle** [comment]
Same there.

**Comment by JoshMayberry** [comment]
This happens to me too

**Comment by benfah** [comment]
Fixed and will be published in newer version :) (Sorrry for the long waiting time!)
