### ISSUE TITLE
[request/bug] Ignore the off-hand when testing whether the player is empty-handed

### ISSUE THREAD

**Issue by Suitov** [benfah/SimpleDrawers#14]
When I have a shield equipped in my off-hand, I can't access a drawer's inventory even when my main hand is empty. If the drawers could ignore the off-hand, this would save a little time equipping and unequipping.

**Comment by benfah** [comment]
Should be fixed now :). The fix will come with the next release.

**Comment by Suitov** [comment]
Thank you!
