### ISSUE TITLE
[bug] Emptied drawers contain 'ghost' items, don't stack with other drawers

### ISSUE THREAD

**Issue by Suitov** [benfah/SimpleDrawers#15]
This one's complex so I tried to document it as clearly as possible...

Note: All the below applied to 2x2 drawers because those were what I had when I tested this.

Observation: When I empty out a drawer and pick it up, it doesn't stack in my inventory with the newly-made drawers of the same wood and same 2x2 configuration.

Observation: I put down one of the previously used drawers and looked at its inventory. One of the empty slots showed the item that was previously in there before I broke and moved the drawer. The quantity was (correctly) marked as 0. The slot in question had not been locked with the drawer key.

Expected behaviour: Emptied slots show as blank/empty on inventory view.

Tried: Left-clicking once on the empty slot to 'withdraw' the item. This did not remove the zero-sized stack from inventory view.

Tried: Putting a random shovel into the slot and immediately removing it. The stack in inventory view now shows the shovel, quantity 0.

Then tried: Looking at a different 4x4 drawer that had previously been filled and emptied, but not (IIRC) ever broken and moved. This drawer also had 0-sized stacks of the items that were previously there.  Suggests that breaking drawers with items still in them was not the cause of the bug, because this drawer hadn't been moved.

**Comment by benfah** [comment]
Hmm, this seems weird, would you mind making some kind of video demonstrating the issue further, because I tried to recreate your issues, but failed :/

**Comment by Suitov** [comment]
Yeah, sorry, this one was a little hard to explain. Demonstration might take me a while, but I'll try.

**Comment by Suitov** [comment]
Ok, here are some screenshots. Three examples. First is the drawer front, showing correctly that there's one empty slot. That's followed by the GUI view, showing the 'ghost' item in the previously emptied slot, with 0 quantity. (Please ignore the screen clutter from REI and Xaero's Minimap...)

Drawers that have been previously filled and then emptied, such that they have these ghost items, don't seem to stack with 'fresh' drawers that haven't been used before.

![2020-08-20_06 59 58](https://user-images.githubusercontent.com/5859840/90861076-1887df00-e383-11ea-8008-e4878af4cfb5.png)
![2020-08-20_07 00 02](https://user-images.githubusercontent.com/5859840/90861082-19207580-e383-11ea-9388-4a7937360b4a.png)
![2020-08-20_07 00 14](https://user-images.githubusercontent.com/5859840/90861084-19b90c00-e383-11ea-8bff-35b72228ba06.png)
![2020-08-20_07 00 17](https://user-images.githubusercontent.com/5859840/90861086-1a51a280-e383-11ea-8856-83874aee3206.png)
![2020-08-20_07 00 34](https://user-images.githubusercontent.com/5859840/90861087-1aea3900-e383-11ea-8edb-069706aa02f1.png)
![2020-08-20_07 00 36](https://user-images.githubusercontent.com/5859840/90861090-1b82cf80-e383-11ea-89cc-617533643fee.png)

**Comment by benfah** [comment]
Should be fixed now, the new version is on the way. :)
Just try to destroy and place the drawers again where the ghost slots were present.

**Comment by Suitov** [comment]
So cool! Thank you.
