### ISSUE TITLE
Hoppers fail to input

### ISSUE THREAD

**Issue by Dragonracer1973** [benfah/SimpleDrawers#2]
Version 1.15.2 1.5.0

**Comment by benfah** [comment]
Could you tell me your exact setup: What hopper used with which item, type of drawer and upgrade, so I can reproduce the issue.

**Comment by Dragonracer1973** [comment]
Sorry I should have done this from the getgo, but with the pandemic, I have had to tend to my child I have several setups, I am semi-automating stone production with Tech reborn furnaces, also my storage setup is chest-hoppers-drawers for easy item sorting. Yes, I am aware that you need to set the output on Tech Reborn machines.
 All this worked fine, in fact, I was hyped when I saw you implemented multi drawers, for my tree setups. 
I am sending a few screenies of my setup all of which worked fine with ver. 1.4.2, once I updated to 1.5.0 they failed to input to the drawers from the hoppers. 
[crash and bug reports.zip](https://github.com/benfah/SimpleDrawers/files/4418021/crash.and.bug.reports.zip)

**Comment by benfah** [comment]
Your bug should be fixed with the next update. Should be out in the next 5 minutes :) (Needing approval from CurseForge)

**Comment by Dragonracer1973** [comment]
thank you
