### ISSUE TITLE
Drawers do not hold their inventories when broken

### ISSUE THREAD

**Issue by Firion88** [benfah/SimpleDrawers#3]
As title says, i was moving my storage to new area and the drawers kep dropping their items when i broke them to move them. Even when locked with the key.

i am using version 1.6.0 on 1.15.2

**Comment by benfah** [comment]
This is intended. Drawers should not be able to hold their items when broken. Also, the key is only for locking the item type of the drawer, not to lock the contents in the drop.

**Comment by Firion88** [comment]
Would it be possible to add an item similar to the original storage drawers packing tape that could enable you to seal the drawer if you decided to move it to a new location?

**Comment by benfah** [comment]
Good idea! I will add this in a future version.
