### ISSUE TITLE
Missing texture on drawer GUI

### ISSUE THREAD

**Issue by Firion88** [benfah/SimpleDrawers#6]
the textures appear to be missing on the GUI screen for the drawers. i have reloaded the textures with F3+T and also removing all texture pack to vanilla and same issue. 
Screenshot attached
![2020-04-20_15 38 13](https://user-images.githubusercontent.com/61030778/79764862-d5a6f380-831d-11ea-8f0f-75338274f8cf.png)

**Comment by Tkvgamer** [comment]
im having the same problem

**Comment by benfah** [comment]
Fixed with 1.7.1, should be out soon when curseforge approves it :)
