### ISSUE TITLE
Crash on putting items into a Drawer: version 1.7.1 for 1.16

### ISSUE THREAD

**Issue by MastaC729** [benfah/SimpleDrawers#8]
Putting items into a drawer creates a NoSuchMethodError when one of your render methods is called:

https://pastebin.com/dTNN1nqE

**Comment by benfah** [comment]
What exact snapshot version are you using?

**Comment by MastaC729** [comment]
I was using the version for 20w13b you posted a few hours ago, assuming you just forgot to change the snapshot number. Everything's working fine on your latest build, sorry for the confusion.

**Comment by benfah** [comment]
Np :)
