### ISSUE TITLE
20w17a Crash on drawer placement

### ISSUE THREAD

**Issue by CodeF53** [benfah/SimpleDrawers#9]
Game crashes when
- 4 item drawer is placed
- Block placed into 1 item drawer

Attempting to reload into the world crashes, giving the same error.
- (all graphic settings crash)

Here is my log https://pastebin.com/KpLd8Zk8

(I can't upgrade to 20w18a because many mods I use don't support it)

**Comment by benfah** [comment]
Simple Drawers is not available for 20w17a, only for 20w18a. It‘s a hassle to keep up with all weekly snapshots. :/
